//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int Eid { get; set; }
        public string EName { get; set; }
        public string Salary { get; set; }
        public string Dob { get; set; }
        public string Gender { get; set; }
        public int DeptDid { get; set; }
    
        public virtual Dept Dept { get; set; }
    }
}
